apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-demo
  template:
    metadata:
      labels:
        app: cloud-demo
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: cloud-demo
        image: cloudopsdemo.azurecr.io/clouddemo:#$(Build.BuildId)#
        ports:
        - containerPort: 8080
          name: cloud-demo
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: cloud-demo